name: Python Environment Setup



on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    - name: Verify Python version
      run: python --version

    - name: Verify flake8 installation
      run: flake8 --version

    - name: Verify pytest installation
      run: pytest --version

